articles/urls.py
from django.urls import path, re_path

from .views import ArticlesList, ArticleDetail, ArticleCreate, ArticleUpdate, ArticleDelete, ArticlesByTagsList, SearchView
from .views import TagAutocomplete, SecurityAutocomplete, BookmarkArticleView, bookmarked_articles
from stocksetfsbonds.models import StockETFBond

app_name = 'articles'

urlpatterns = [
    path('tag-autocomplete/', TagAutocomplete.as_view(), name='tag-autocomplete'),
    path('security-autocomplete/', SecurityAutocomplete.as_view(), name='security-autocomplete'),
    path('', ArticlesList.as_view(), name='list_view'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('<tag>/', ArticlesByTagsList.as_view(), name='articles_by_tags'),
    path('articles/create/', ArticleCreate.as_view(), name='create_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/$', ArticleDetail.as_view(), name='detail_view'),
    # path('articles/<slug:slug>', ArticleDetail.as_view(), name='detail_view'),

    # path('articles/<slug:slug>/', ArticleUpdate.as_view(), name='update_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/update/$', ArticleUpdate.as_view(), name='update_view'),
    # path('articles/<slug:slug>/delete/', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/delete/$', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^bookmark/(?P<slug>[\w-]+)/$', BookmarkArticleView, name='bookmark_article'),
    # path('bookmark/<slug:slug>', BookmarkArticleView, name='bookmark_article'),
    path('bookmarked/articles/', bookmarked_articles, name='bookmarked_articles'),
]

stocksetfsbonds/urls.py
from django.urls import path

from .views import SecuritiesList, SecurityDetail, SecurityCreate, Watchlist, WatchlistView, SecurityUpdate

app_name = 'securities'

urlpatterns = [
    path('create/', SecurityCreate.as_view(), name='security_create'),
    path('update/<slug:slug>', SecurityUpdate.as_view(), name='security_update'),
    path('<slug:slug>/', SecuritiesList.as_view(), name='securities_list'),
    path('<slug:slug>', SecurityDetail.as_view(), name='security_detail'),
    path('watchlist/<slug:slug>', Watchlist, name='in_watchlist'),
    path('watchlist/securities/', WatchlistView, name='watchlist'),
]

users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, profile, ChangeUserInfoView, UserPasswordChangeVeiw, RegisterUserView, RegisterDoneView
from .views import DeleteUserView, ProfileView, PrivacyView


app_name = 'users'

urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    # path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    # path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    # path('accounts/profile/<username>/', ProfileView.as_view(), name='profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/<username>/', ProfileView.as_view(), name='profile_view'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', UserPasswordChangeVeiw.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('privacy', PrivacyView.as_view(), name='privacy'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articles.views import TagAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('securities/', include('stocksetfsbonds.urls')),
    path('', include('users.urls')),

    path('comments/', include('django_comments.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articles/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from django_extensions.db.fields import AutoSlugField
from taggit.managers import TaggableManager
# from autoslug import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField

from stocksetfsbonds.models import StockETFBond
from users.models import AdvUser
from .utilities import article_img_directory_path, article_slugify_function



class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = AutoSlugField(populate_from='title', editable=True, verbose_name='Слаг',
                         help_text='То, как будет выглядеть URL адрес статьи. Можно не указывать',
                         slugify_function=article_slugify_function, allow_unicode=True)
    author = models.ForeignKey(AdvUser, verbose_name='автор', on_delete=models.CASCADE)
    title_image = models.ImageField(verbose_name='Титульное изображение', blank=True, upload_to=article_img_directory_path)
    description = models.TextField(verbose_name='Краткое описание')
    body = models.TextField(verbose_name='Текст')
    post_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    update_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления публикации')
    tags = TaggableManager(verbose_name='Теги', help_text='Теги через запятую', blank=True)
    stocks_etfs_or_bonds = models.ManyToManyField(StockETFBond, blank=True, verbose_name='Ценная бумага')
    published = models.BooleanField(verbose_name='Опубликовано', default=True, db_index=True)
    bookmark = models.ManyToManyField(AdvUser, related_name='bookmarked_by_user', blank=True,
                                      verbose_name='Читать позже')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ['-post_date']

    def __str__(self):
        return self.title

    # You don’t even need to provide a success_url
    # for CreateView or UpdateView - they will use get_absolute_url() on the model object if available.
    def get_absolute_url(self):
        return reverse('articles:detail_view', kwargs={'slug': self.slug})

    def total_bookmark(self):
        return self.bookmark.count()

articles/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, CheckboxSelectMultiple, ImageField, HiddenInput
from django import forms

from .models import Article
from stocksetfsbonds.models import StockETFBond

from dal import autocomplete
from taggit.models import Tag
from ckeditor.widgets import CKEditorWidget


# class ArticleForm(ModelForm):
class ArticleForm(autocomplete.FutureModelForm):
    # stocks_etfs_or_bonds = ModelMultipleChoiceField(queryset=StockETFBond.objects.all(),
    #                                                 widget=CheckboxSelectMultiple, required=False)
    title_image = ImageField(required=False)
    body = forms.CharField(widget=CKEditorWidget(), label='')

    class Meta:
        model = Article
        fields = ('title', 'author', 'title_image', 'description', 'body', 'tags', 'stocks_etfs_or_bonds', 'published')
        widgets = {'author': HiddenInput,
                   'tags': autocomplete.TaggitSelect2('articles:tag-autocomplete'),
                   'stocks_etfs_or_bonds': autocomplete.ModelSelect2Multiple(url='articles:security-autocomplete'),
                   }

articles/views.py
from django.core.exceptions import PermissionDenied
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Count, Q, F
from itertools import chain
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from taggit.models import Tag
from dal import autocomplete

from .models import Article
from .forms import ArticleForm
from stocksetfsbonds.models import StocksETFsBonds
from stocksetfsbonds.models import StockETFBond
from users.models import AdvUser


def BookmarkArticleView(request, slug):
    article = get_object_or_404(Article, id=request.POST.get('article_id'))
    bookmarked = False
    if article.bookmark.filter(id=request.user.id).exists():
        article.bookmark.remove(request.user)
        bookmarked = False
    else:
        article.bookmark.add(request.user)
        bookmarked = True
    # return HttpResponseRedirect(reverse('articles:detail_view', args=[str(slug)]))
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))


class TagAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = Tag.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


class SecurityAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = StockETFBond.objects.all()

        if self.q:
            qs = qs.filter(ticker__istartswith=self.q) | qs.filter(name__istartswith=self.q)

        return qs



class ArticlesList(ListView):
    model = Article
    template_name = 'articles/list_view.html'
    context_object_name = 'articles_list'
    articles_quantiy = Tag.objects.annotate(Count('taggit_taggeditem_items'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        context['articles_list'] = Article.objects.filter(published=True)[:20]
        return context


class ArticleDetail(DetailView):
    model = Article
    template_name = 'articles/detail_view.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)

        stuff = get_object_or_404(Article, slug=self.kwargs['slug'])
        bookmarked = False
        if stuff.bookmark.filter(id=self.request.user.id).exists():
            bookmarked = True
        context["bookmarked"] = bookmarked

        self.object.views = F('views') + 1
        self.object.save()
        self.object.refresh_from_db()

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context


class ArticleCreate(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'articles/create_view.html'
    # fields = ['title', 'description', 'body', 'tags', 'stocks_etfs_or_bonds']
    form_class = ArticleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context

    def get_initial(self):
        initial = super(ArticleCreate, self).get_initial()
        initial = initial.copy()
        initial['author'] = self.request.user.pk
        return initial


class ArticleUpdate(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = 'articles/update_view.html'
    # fields = ['title', 'description', 'body', 'tags']
    context_object_name = 'article_update'
    form_class = ArticleForm

    def setup(self, request, *args, **kwargs):
        self.author = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context

    def get_queryset(self):
        author = super(ArticleUpdate, self).get_queryset()
        return author.filter(author=self.request.user)


class ArticleDelete(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'articles/delete_view.html'
    success_url = reverse_lazy('articles:list_view')
    context_object_name = 'article_delete'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        return context

    def get_queryset(self):
        author = super(ArticleDelete, self).get_queryset()
        return author.filter(author=self.request.user)


class ArticlesByTagsList(ListView):

    template_name = 'articles/articles_by_tags.html'
    context_object_name = 'articles_list'


    # работает
    # def get_queryset(self):
    #     return TaggedItem.objects.filter(tag_id=self.kwargs['tag_id'])


    # def get_queryset(self):
    #     return TaggedItem.objects.filter(tag=self.kwargs['tag'])

    def get_queryset(self):
        return Article.objects.filter(published=True, tags__name=self.kwargs['tag'])

    # def get_queryset(self):
    #     self.slug = get_object_or_404(Tag, name=self.kwargs['slug'])
    #     return Article.objects.filter(slug=self.slug)
    #
    # рабочий вариант (почти)
    # def get_queryset(self):
    #     self.tag = get_object_or_404(Tag, name=self.kwargs['tag'])
    #     return Article.objects.filter(slug=self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]

        # заголовок списка по тегу
        context['current_tag'] = Tag.objects.get(name=self.kwargs['tag'])
        return context

class SearchView(ListView):
    template_name = 'articles/search_view.html'

    def get_queryset(self):
        query = self.request.GET.get('q')

        object_list = Article.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)|
                                             Q(body__icontains=query) |
                                             Q(stocks_etfs_or_bonds__ticker__icontains=query) |
                                             Q(stocks_etfs_or_bonds__description__icontains=query) |
                                             Q(stocks_etfs_or_bonds__name__icontains=query) |
                                             Q(tags__name__icontains=query), published=True)
        # securities_list = StockETFBond.objects.filter(Q(name__icontains=query))
        # search_result = list(chain(object_list, securities_list))
        # return list(chain(object_list, securities_list))
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()

        query = self.request.GET.get('q')
        context['securities_list'] = StockETFBond.objects.filter(Q(name__icontains=query) |
                                                                 Q(ticker__icontains=query) |
                                                                 Q(description__icontains=query))
        context['users_list'] = AdvUser.objects.filter(Q(username__icontains=query) |
                                                                 Q(first_name__icontains=query) |
                                                                 Q(last_name__icontains=query))
        # context['articles_list'] = Article.objects.all()[:10]
        return context


# class BookmarkedArticlesView(TemplateView):

articles/templates/layout/basic.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'articles/css/style.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
    {% bootstrap_css %}

    <style>
        .django-ckeditor-widget {
  width: 100%;
}
    </style>

</head>

<body class="d-flex flex-column min-vh-100">



    <header class="p-3 border-bottom ">
        <div class="container-fluid d-grid gap-3 align-items-center">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a id="home" href="/" class="navbar-brand pb-2 d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
              <em class="text-primary">Stocks</em>
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% for name in securities_types_list %}
                    <li><a href="{% url 'securities:securities_list' name.slug %}" class="nav-link px-2 link-dark">{{ name }}</a></li>
                {% endfor %}

                <div class="btn-group ms-3">
                    <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'articles:create_view' %}">Новая публикация</a></li>
                        <li><a class="dropdown-item" href="{% url 'securities:security_create' %}">Добавить ценную бумагу</a></li>
                    </ul>
                </div>
            </ul>

            <form action="{% url 'articles:search_view' %}" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
              <input name="q" type="search" class="form-control" placeholder="Search..." aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                      {% if user.photo %}
                            <img src="{{ user.photo.url }}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">
                      {% else %}
                            <i class="bi bi-person-circle" style="font-size: 32px;"></i>
                      {% endif %}
                  </a>
                  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                    <span class="dropdown-item text-secondary"><em>@{{ user.username }}</em></span>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'articles:bookmarked_articles' %}"><i class="bi bi-book me-1"></i>Читать позже</a></li>
                    <li><a class="dropdown-item" href="{% url 'securities:watchlist' %}"><i class="bi bi-bookmark-star me-1"></i>Список наблюдения</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:profile' %}"><i class="bi bi-file-earmark-person me-1"></i>Профиль</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:profile_change' %}"><i class="bi bi-pencil me-1"></i>Изменить личные данные</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}"><i class="bi bi-box-arrow-right me-1"></i>Выход</a></li>
                  </ul>
                </div>
            {% else %}
              <div class="text-end">
                <a class="btn btn-outline-primary me-2" href="{% url 'users:login' %}" role="button">Войти</a>
                <a class="btn btn-primary" href="{% url 'users:register' %}" role="button">Регистрация</a>
              </div>
            {% endif %}

          </div>
        </div>
    </header>

    <div class="container mb-md-4">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-3  mb-md-0">
            {% for tag in tags_list %}
                <li><a href="{% url 'articles:articles_by_tags' tag %}" class="nav-link px-3 link-secondary">#{{ tag }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <div class="container mb-5">

        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}

        {% block content %}
        {% endblock %}

    </div>

    <footer class="footer mt-auto py-3 border-top">
  <div class="container my-4">
    <span class="text-muted d-flex justify-content-center">
        <span>
            © 2021 <a class="text-decoration-none link-secondary" href="/"><em>Stocks</em></a>

        </span>
        <span class="mx-auto ">
            <a class="text-muted text-decoration-none" href="{% url 'users:privacy' %}">
<!--                <i class="bi bi-shield me-1"></i>-->
                Политика конфиденциальности
            </a>
            <br>
            <a class="text-muted text-decoration-none" href="mailto:stocksabout@yahoo.com">
<!--                <i class="bi bi-envelope me-1"></i>-->
                stocksabout@yahoo.com</a>
        </span>
        <span>
            <a href="#home" role="button"><i class="bi bi-arrow-up-circle text-muted fs-4"></i></a>
        </span>
    </span>
  </div>
</footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>