articles/urls.py
from django.urls import path, re_path

from .views import ArticlesList, ArticleDetail, ArticleCreate, ArticleUpdate, ArticleDelete, ArticlesByTagsList, SearchView
from .views import TagAutocomplete, SecurityAutocomplete, BookmarkArticleView, bookmarked_articles
from stocksetfsbonds.models import StockETFBond

app_name = 'articles'

urlpatterns = [
    path('tag-autocomplete/', TagAutocomplete.as_view(), name='tag-autocomplete'),
    path('security-autocomplete/', SecurityAutocomplete.as_view(), name='security-autocomplete'),
    path('', ArticlesList.as_view(), name='list_view'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('<tag>/', ArticlesByTagsList.as_view(), name='articles_by_tags'),
    path('articles/create/', ArticleCreate.as_view(), name='create_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/$', ArticleDetail.as_view(), name='detail_view'),
    # path('articles/<slug:slug>', ArticleDetail.as_view(), name='detail_view'),

    # path('articles/<slug:slug>/', ArticleUpdate.as_view(), name='update_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/update/$', ArticleUpdate.as_view(), name='update_view'),
    # path('articles/<slug:slug>/delete/', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/delete/$', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^bookmark/(?P<slug>[\w-]+)/$', BookmarkArticleView, name='bookmark_article'),
    # path('bookmark/<slug:slug>', BookmarkArticleView, name='bookmark_article'),
    path('bookmarked/articles/', bookmarked_articles, name='bookmarked_articles'),
]

stocksetfsbonds/urls.py
from django.urls import path

from .views import SecuritiesList, SecurityDetail, SecurityCreate, Watchlist, WatchlistView, SecurityUpdate

app_name = 'securities'

urlpatterns = [
    path('create/', SecurityCreate.as_view(), name='security_create'),
    path('update/<slug:slug>', SecurityUpdate.as_view(), name='security_update'),
    path('<slug:slug>/', SecuritiesList.as_view(), name='securities_list'),
    path('<slug:slug>', SecurityDetail.as_view(), name='security_detail'),
    path('watchlist/<slug:slug>', Watchlist, name='in_watchlist'),
    path('watchlist/securities/', WatchlistView, name='watchlist'),
]

users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, profile, ChangeUserInfoView, UserPasswordChangeVeiw, RegisterUserView, RegisterDoneView
from .views import DeleteUserView, ProfileView, PrivacyView


app_name = 'users'

urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    # path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    # path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    # path('accounts/profile/<username>/', ProfileView.as_view(), name='profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/<username>/', ProfileView.as_view(), name='profile_view'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', UserPasswordChangeVeiw.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('privacy', PrivacyView.as_view(), name='privacy'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articles.views import TagAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('securities/', include('stocksetfsbonds.urls')),
    path('', include('users.urls')),

    path('comments/', include('django_comments.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stocksetfsbonds/models.py
from django.db import models
from django.urls import reverse

from django_extensions.db.fields import AutoSlugField

from users.models import AdvUser
from .utilities import security_img_directory_path, security_slugify_function


class StocksETFsBonds(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название')
    # slug = models.SlugField(unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True, verbose_name='Слаг')
    icon = models.ImageField(blank=True, verbose_name='Иконка', upload_to=security_img_directory_path)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип ценной бумаги'
        verbose_name_plural = 'Типы ценных бумаг'


class StockETFBond(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название')
    slug = AutoSlugField(populate_from='ticker', unique=True, verbose_name='Слаг', slugify_function=security_slugify_function)
    stocketforbond = models.ForeignKey(StocksETFsBonds, on_delete=models.PROTECT, verbose_name='Тип')
    ticker = models.CharField(max_length=10, unique=True, verbose_name='Тикер')
    icon = models.ImageField(upload_to=security_img_directory_path, blank=True, verbose_name='Логотип')
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    watchlist = models.ManyToManyField(AdvUser, blank=True, verbose_name='Список наблюдения')

    def __str__(self):
        return self.ticker


    class Meta:
        verbose_name = 'Ценная бумага'
        verbose_name_plural = 'Ценные бумаги'

    # You don’t even need to provide a success_url
    # for CreateView or UpdateView - they will use get_absolute_url() on the model object if available.
    def get_absolute_url(self):
        return reverse('securities:security_detail', kwargs={'slug': self.slug})

stocksetfsbonds/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import StockETFBond, StocksETFsBonds
from articles.models import Article

from .tiingo import get_meta_data, get_price, get_daily_data, get_additional_data


from taggit.models import Tag

class SecuritiesList(ListView):

    template_name = 'stocksetfsbonds/securities_list.html'
    context_object_name = 'securities_list'

    # список бумаг по категории
    def get_queryset(self):
        return StockETFBond.objects.filter(stocketforbond__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]

        # заголовок с названием типа ценной бумаги
        context['current_type'] = StocksETFsBonds.objects.get(slug=self.kwargs['slug'])
        return context


class SecurityDetail(DetailView):
    model = StockETFBond
    template_name = 'stocksetfsbonds/security_detail.html'
    context_object_name = 'security'

    # def get_queryset(self):
    #     return Article.objects.filter(stocks_etfs_or_bonds__name=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]

        # for tiingo
        context['ticker'] = StockETFBond.objects.get(ticker=self.object.ticker)
        context['meta'] = get_meta_data(StockETFBond.objects.get(ticker=self.object.ticker))
        context['price'] = get_price(StockETFBond.objects.get(ticker=self.object.ticker))
        security_daily_data = get_daily_data(StockETFBond.objects.get(ticker=self.object.ticker))
        context['daily_data'] = security_daily_data

        # context['additional_data'] = get_additional_data()

        stuff = get_object_or_404(StockETFBond, slug=self.kwargs['slug'])
        in_watchlist = False
        if stuff.watchlist.filter(id=self.request.user.id).exists():
            in_watchlist = True
        context["watchlist"] = in_watchlist


        # вывод связанных статей
        context['articles_list'] = Article.objects.filter(stocks_etfs_or_bonds__slug=self.kwargs['slug'], published=True)
        return context


class SecurityCreate(LoginRequiredMixin, CreateView):
    model = StockETFBond
    template_name = 'stocksetfsbonds/security_create.html'
    context_object_name = 'security'
    fields = ('name', 'stocketforbond', 'ticker', 'icon', 'description')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context


class SecurityUpdate(LoginRequiredMixin, UpdateView):
    model = StockETFBond
    template_name = 'stocksetfsbonds/security_create.html'
    context_object_name = 'security'
    fields = ('ticker', 'icon', 'description')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context


def Watchlist(request, slug):
    secuirity = get_object_or_404(StockETFBond, id=request.POST.get('stocketfbond_id'))
    in_watchlist = False
    if secuirity.watchlist.filter(id=request.user.id).exists():
        secuirity.watchlist.remove(request.user)
        in_watchlist = False
    else:
        secuirity.watchlist.add(request.user)
        in_watchlist = True
    # return HttpResponseRedirect(reverse('articles:detail_view', args=[str(slug)]))
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))


@login_required
def WatchlistView(request):
    in_watchlist = StockETFBond.objects.filter(watchlist=request.user.pk)
    tags_list = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
        '-articles_quantiy')[:10]
    securities_types_list = StocksETFsBonds.objects.all()
    context = {'in_watchlist': in_watchlist, 'tags_list': tags_list, 'securities_types_list': securities_types_list,}

    return render(request, 'stocksetfsbonds/watchlist_view.html', context)

stocksetfsbonds/templates/stocksetfsbonds/securities_list.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %}
    {{ current_type }}
{% endblock %}

{% block content %}

    <h1 class="mb-4">
        {% if current_type.icon %}
            <img class="pb-3" src="{{ current_type.icon.url }}" width="48" alt="{{ current_type }}">
        {% endif %}
        {{ current_type }}
    </h1>


    <table class="table table-hover align-middle  border">
<!--      <thead>-->
<!--        <tr>-->
<!--          <th scope="col"></th>-->
<!--          <th scope="col">Name</th>-->
<!--          <th scope="col">Ticker</th>-->
<!--        </tr>-->
<!--      </thead>-->
      <tbody>
        {% for security in securities_list %}
            <tr>
              <th scope="row">
                  {% if security.icon %}
                    <img class="mx-auto d-block" src="{{ security.icon.url }}" width="24" alt="{{ security.icon }}">
                  {% else %}
                    <img width="24" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="mx-auto d-block">
                  {% endif %}
              </th>
              <td>
                  <a href="{% url 'securities:security_detail' security.slug %}">
                    {{ security.ticker }}
                  </a>
              </td>
              <td>
                  <a href="{% url 'securities:security_detail' security.slug %}">
                    {{ security.name }}
                  </a>
              </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>



{% endblock %}

stocksetfsbonds/templates/stocksetfsbonds/security_create.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    Добавить ценную бумагу
{% endblock %}

{% block content %}

    <h1 class="mb-4">Добавление ценной бумаги</h1>

    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {% bootstrap_button button_type="submit" content="Добавить" %}
    </form>

    <br>
    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

stocksetfsbonds/templates/stocksetfsbonds/security_detail.html
{% extends 'layout/basic.html' %}

{% load static %}
{% load humanize %}
{% load tz %}

{% block title %}
    {{ security.name }}
{% endblock %}

{% block content %}

    <div class="card mb-5">
        <div class="row p-4">

            <div class="card-body col-md-6 pe-4">
                    <div class="row">
                        <div class="col-sm-2">
                            {% if security.icon %}
                                <img class="align-bottom" src="{{ security.icon.url }}" width="64" alt="{{ security.name }}">
                            {% else %}
                                <img width="64" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                            {% endif %}
                        </div>
                        <div class="col-sm-10">
                            <div class="d-flex">
                                <span>
                                    <h1>
                                        {{ security.name }}
                                    </h1>
                                    <small>
                                        {{ security.ticker }}
                                    </small>
                                </span>

                                <span class="me-5">

                                    <form class="ms-1" action="{% url 'securities:in_watchlist' security.slug %}" method="post">
                                        {% csrf_token %}
                                        {% if user.is_authenticated %}
                                            {% if watchlist %}
                                                <button class="btn pb-2" type="submit" name="stocketfbond_id" value="{{ security.id }}">
                                                    <i class="bi bi-check-circle-fill text-success fs-3"></i><i class="bi "></i>
                                                </button>
                                            {% else %}
                                                <button class="btn" type="submit" name="stocketfbond_id" value="{{ security.id }}">
                                                    <i class="bi bi-plus-circle text-dark fs-3"></i>
                                                </button>
                                            {% endif %}
                                        {% endif %}
                                    </form>
                                </span>
                                {% if price %}
                                <span class="ms-auto text-dark">
                                    <h1>
                                        ${{ price.close }}
                                    </h1>
                                </span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="mt-4">
                            {% if user.is_authenticated %}
                                {% if not security.icon or not security.ticker or not security.description %}
                                    <a href="{% url 'securities:security_update' security.slug %}">Обновить данные</a>
                                {% endif %}
                            {% endif %}
                            <p>
                                {% if security.description %}
                                    {{ security.description }}
                                {% else %}
                                    {{ meta.description }}
                                {% endif %}
                            </p>

                        </div>
                    </div>
            </div>

            <div class="card-body col-md-6 ps-md-5 pb-md-5">
                <br class="md">
                <br class="md">
                <table class="table table-hover mt-md-5">

                  <tbody>
                    {% if daily_data %}
                        {% for daily_data in daily_data %}
                            {% if forloop.last %}
                                {% if daily_data.marketCap %}
                                    <tr>
                                        <th scope="row">Рыночная капитализация</th>
                                        <td>{{ daily_data.marketCap|intword }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">PE</th>
                                        <td>{{ daily_data.peRatio|intword }}</td>
                                    </tr>
                                                                    <tr>
                                        <th scope="row">PB</th>
                                        <td>{{ daily_data.pbRatio|intword }}</td>
                                    </tr>
                                                                 <tr>
                                        <th scope="row">PEG</th>
                                        <td>{{ daily_data.trailingPEG1Y|floatformat }}</td>
                                    </tr>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>



    {% for article in articles_list %}

        <div class="card mb-3 bg-light">
            <div class="card-body">
                <small>
                    {% if user.is_superuser %}
                        <span class="text-secondary me-1"><i class="bi bi-eye-fill me-1"></i>{{ article.views }}</span>
                    {% endif %}
                    {% for tag in article.tags.all %}
                        <a class="text-decoration-none me-1" href="{% url 'articles:articles_by_tags' tag %}">#{{ tag }}</a>
                    {% endfor %}
                </small>
                <h1>
                    <a class="text-decoration-none" href="{% url 'articles:detail_view' article.slug %}">{{ article }}</a>
                </h1>
                <small class="me-1 text-secondary">
                    <b class="me-1">{{ article.post_date|naturalday }}</b>
                    {% if article.author.is_superuser %}
                    <span class="badge bg-dark text-secondary me-1"><em>{{ request.get_host }}</em></span>
                    {% else %}
                    <a style="text-decoration: none;" class="link-secondary me-1" href="{% url 'users:profile_view' article.author.username %}"><em>@{{ article.author.username }}</em></a>
                    {% endif %}
                </small>
                {% if user == article.author %}
                <small>
                    <a href="{% url 'articles:update_view' article.slug %}">Обновить</a>
                    <a href="{% url 'articles:delete_view' article.slug %}">Удалить</a>
                </small>
                {% endif %}
                <p class="mt-4">
                    {{ article.description }}
                </p>
                {% for security in article.stocks_etfs_or_bonds.all %}
                    <span class="badge border bg-light text-dark">
                        {% if security.icon %}
                            <img src="{{ security.icon.url }}" width="16" alt="{{ security.icon }}" class="align-bottom">
                        {% else %}
                            <img width="16" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                        {% endif %}
                        <a class="text-decoration-none" href="{% url 'securities:security_detail' security.slug %}">
                            {{ security.ticker }}
                        </a>
                    </span>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

stocksetfsbonds/templates/stocksetfsbonds/watchlist_view.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %}
    Список наблюдения
{% endblock %}

{% block content %}

    <h1 class="mb-4">

        <i class="bi bi-bookmark-star me-3"></i>Список наблюдения
    </h1>


    <table class="table table-hover align-middle  border">
<!--      <thead>-->
<!--        <tr>-->
<!--          <th scope="col"></th>-->
<!--          <th scope="col">Name</th>-->
<!--          <th scope="col">Ticker</th>-->
<!--        </tr>-->
<!--      </thead>-->
      <tbody>
        {% for security in in_watchlist %}
            <tr>
              <th scope="row">
                  {% if security.icon %}
                    <img class="mx-auto d-block" src="{{ security.icon.url }}" width="24" alt="{{ security.icon }}">
                  {% else %}
                    <img width="24" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="mx-auto d-block">
                  {% endif %}
              </th>
              <td>
                  <a href="{% url 'securities:securities_list' security.stocketforbond.slug %}">
                    {{ security.stocketforbond }}
                  </a>
              </td>
              <td>
                  <a href="{% url 'securities:security_detail' security.slug %}">
                    {{ security.ticker }}
                  </a>
              </td>
              <td>
                  <a href="{% url 'securities:security_detail' security.slug %}">
                    {{ security.name }}
                  </a>
              </td>

            </tr>
        {% endfor %}
      </tbody>
    </table>



{% endblock %}