articles/urls.py
from django.urls import path, re_path

from .views import ArticlesList, ArticleDetail, ArticleCreate, ArticleUpdate, ArticleDelete, ArticlesByTagsList, SearchView
from .views import TagAutocomplete, SecurityAutocomplete, BookmarkArticleView, bookmarked_articles
from stocksetfsbonds.models import StockETFBond

app_name = 'articles'

urlpatterns = [
    path('tag-autocomplete/', TagAutocomplete.as_view(), name='tag-autocomplete'),
    path('security-autocomplete/', SecurityAutocomplete.as_view(), name='security-autocomplete'),
    path('', ArticlesList.as_view(), name='list_view'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('<tag>/', ArticlesByTagsList.as_view(), name='articles_by_tags'),
    path('articles/create/', ArticleCreate.as_view(), name='create_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/$', ArticleDetail.as_view(), name='detail_view'),
    # path('articles/<slug:slug>', ArticleDetail.as_view(), name='detail_view'),

    # path('articles/<slug:slug>/', ArticleUpdate.as_view(), name='update_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/update/$', ArticleUpdate.as_view(), name='update_view'),
    # path('articles/<slug:slug>/delete/', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/delete/$', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^bookmark/(?P<slug>[\w-]+)/$', BookmarkArticleView, name='bookmark_article'),
    # path('bookmark/<slug:slug>', BookmarkArticleView, name='bookmark_article'),
    path('bookmarked/articles/', bookmarked_articles, name='bookmarked_articles'),
]

stocksetfsbonds/urls.py
from django.urls import path

from .views import SecuritiesList, SecurityDetail, SecurityCreate, Watchlist, WatchlistView, SecurityUpdate

app_name = 'securities'

urlpatterns = [
    path('create/', SecurityCreate.as_view(), name='security_create'),
    path('update/<slug:slug>', SecurityUpdate.as_view(), name='security_update'),
    path('<slug:slug>/', SecuritiesList.as_view(), name='securities_list'),
    path('<slug:slug>', SecurityDetail.as_view(), name='security_detail'),
    path('watchlist/<slug:slug>', Watchlist, name='in_watchlist'),
    path('watchlist/securities/', WatchlistView, name='watchlist'),
]

users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, profile, ChangeUserInfoView, UserPasswordChangeVeiw, RegisterUserView, RegisterDoneView
from .views import DeleteUserView, ProfileView, PrivacyView


app_name = 'users'

urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    # path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    # path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    # path('accounts/profile/<username>/', ProfileView.as_view(), name='profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/<username>/', ProfileView.as_view(), name='profile_view'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', UserPasswordChangeVeiw.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('privacy', PrivacyView.as_view(), name='privacy'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articles.views import TagAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('securities/', include('stocksetfsbonds.urls')),
    path('', include('users.urls')),

    path('comments/', include('django_comments.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articles/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from django_extensions.db.fields import AutoSlugField
from taggit.managers import TaggableManager
# from autoslug import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField

from stocksetfsbonds.models import StockETFBond
from users.models import AdvUser
from .utilities import article_img_directory_path, article_slugify_function



class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = AutoSlugField(populate_from='title', editable=True, verbose_name='Слаг',
                         help_text='То, как будет выглядеть URL адрес статьи. Можно не указывать',
                         slugify_function=article_slugify_function, allow_unicode=True)
    author = models.ForeignKey(AdvUser, verbose_name='автор', on_delete=models.CASCADE)
    title_image = models.ImageField(verbose_name='Титульное изображение', blank=True, upload_to=article_img_directory_path)
    description = models.TextField(verbose_name='Краткое описание')
    body = models.TextField(verbose_name='Текст')
    post_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    update_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления публикации')
    tags = TaggableManager(verbose_name='Теги', help_text='Теги через запятую', blank=True)
    stocks_etfs_or_bonds = models.ManyToManyField(StockETFBond, blank=True, verbose_name='Ценная бумага')
    published = models.BooleanField(verbose_name='Опубликовано', default=True, db_index=True)
    bookmark = models.ManyToManyField(AdvUser, related_name='bookmarked_by_user', blank=True,
                                      verbose_name='Читать позже')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ['-post_date']

    def __str__(self):
        return self.title

    # You don’t even need to provide a success_url
    # for CreateView or UpdateView - they will use get_absolute_url() on the model object if available.
    def get_absolute_url(self):
        return reverse('articles:detail_view', kwargs={'slug': self.slug})

    def total_bookmark(self):
        return self.bookmark.count()

articles/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, CheckboxSelectMultiple, ImageField, HiddenInput
from django import forms

from .models import Article
from stocksetfsbonds.models import StockETFBond

from dal import autocomplete
from taggit.models import Tag
from ckeditor.widgets import CKEditorWidget


# class ArticleForm(ModelForm):
class ArticleForm(autocomplete.FutureModelForm):
    # stocks_etfs_or_bonds = ModelMultipleChoiceField(queryset=StockETFBond.objects.all(),
    #                                                 widget=CheckboxSelectMultiple, required=False)
    title_image = ImageField(required=False)
    body = forms.CharField(widget=CKEditorWidget(), label='')

    class Meta:
        model = Article
        fields = ('title', 'author', 'title_image', 'description', 'body', 'tags', 'stocks_etfs_or_bonds', 'published')
        widgets = {'author': HiddenInput,
                   'tags': autocomplete.TaggitSelect2('articles:tag-autocomplete'),
                   'stocks_etfs_or_bonds': autocomplete.ModelSelect2Multiple(url='articles:security-autocomplete'),
                   }

articles/views.py
from django.core.exceptions import PermissionDenied
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Count, Q, F
from itertools import chain
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from taggit.models import Tag
from dal import autocomplete

from .models import Article
from .forms import ArticleForm
from stocksetfsbonds.models import StocksETFsBonds
from stocksetfsbonds.models import StockETFBond
from users.models import AdvUser


def BookmarkArticleView(request, slug):
    article = get_object_or_404(Article, id=request.POST.get('article_id'))
    bookmarked = False
    if article.bookmark.filter(id=request.user.id).exists():
        article.bookmark.remove(request.user)
        bookmarked = False
    else:
        article.bookmark.add(request.user)
        bookmarked = True
    # return HttpResponseRedirect(reverse('articles:detail_view', args=[str(slug)]))
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))


class TagAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = Tag.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


class SecurityAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = StockETFBond.objects.all()

        if self.q:
            qs = qs.filter(ticker__istartswith=self.q) | qs.filter(name__istartswith=self.q)

        return qs



class ArticlesList(ListView):
    model = Article
    template_name = 'articles/list_view.html'
    context_object_name = 'articles_list'
    articles_quantiy = Tag.objects.annotate(Count('taggit_taggeditem_items'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        context['articles_list'] = Article.objects.filter(published=True)[:20]
        return context


class ArticleDetail(DetailView):
    model = Article
    template_name = 'articles/detail_view.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)

        stuff = get_object_or_404(Article, slug=self.kwargs['slug'])
        bookmarked = False
        if stuff.bookmark.filter(id=self.request.user.id).exists():
            bookmarked = True
        context["bookmarked"] = bookmarked

        self.object.views = F('views') + 1
        self.object.save()
        self.object.refresh_from_db()

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context


class ArticleCreate(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'articles/create_view.html'
    # fields = ['title', 'description', 'body', 'tags', 'stocks_etfs_or_bonds']
    form_class = ArticleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context

    def get_initial(self):
        initial = super(ArticleCreate, self).get_initial()
        initial = initial.copy()
        initial['author'] = self.request.user.pk
        return initial


class ArticleUpdate(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = 'articles/update_view.html'
    # fields = ['title', 'description', 'body', 'tags']
    context_object_name = 'article_update'
    form_class = ArticleForm

    def setup(self, request, *args, **kwargs):
        self.author = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        return context

    def get_queryset(self):
        author = super(ArticleUpdate, self).get_queryset()
        return author.filter(author=self.request.user)


class ArticleDelete(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'articles/delete_view.html'
    success_url = reverse_lazy('articles:list_view')
    context_object_name = 'article_delete'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        return context

    def get_queryset(self):
        author = super(ArticleDelete, self).get_queryset()
        return author.filter(author=self.request.user)


class ArticlesByTagsList(ListView):

    template_name = 'articles/articles_by_tags.html'
    context_object_name = 'articles_list'


    # работает
    # def get_queryset(self):
    #     return TaggedItem.objects.filter(tag_id=self.kwargs['tag_id'])


    # def get_queryset(self):
    #     return TaggedItem.objects.filter(tag=self.kwargs['tag'])

    def get_queryset(self):
        return Article.objects.filter(published=True, tags__name=self.kwargs['tag'])

    # def get_queryset(self):
    #     self.slug = get_object_or_404(Tag, name=self.kwargs['slug'])
    #     return Article.objects.filter(slug=self.slug)
    #
    # рабочий вариант (почти)
    # def get_queryset(self):
    #     self.tag = get_object_or_404(Tag, name=self.kwargs['tag'])
    #     return Article.objects.filter(slug=self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # необходимы для показа списка тэгов и типов бумаг в хедере
        # context['tags_list'] = Tag.objects.all()
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]

        # заголовок списка по тегу
        context['current_tag'] = Tag.objects.get(name=self.kwargs['tag'])
        return context

class SearchView(ListView):
    template_name = 'articles/search_view.html'

    def get_queryset(self):
        query = self.request.GET.get('q')

        object_list = Article.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)|
                                             Q(body__icontains=query) |
                                             Q(stocks_etfs_or_bonds__ticker__icontains=query) |
                                             Q(stocks_etfs_or_bonds__description__icontains=query) |
                                             Q(stocks_etfs_or_bonds__name__icontains=query) |
                                             Q(tags__name__icontains=query), published=True)
        # securities_list = StockETFBond.objects.filter(Q(name__icontains=query))
        # search_result = list(chain(object_list, securities_list))
        # return list(chain(object_list, securities_list))
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()

        query = self.request.GET.get('q')
        context['securities_list'] = StockETFBond.objects.filter(Q(name__icontains=query) |
                                                                 Q(ticker__icontains=query) |
                                                                 Q(description__icontains=query))
        context['users_list'] = AdvUser.objects.filter(Q(username__icontains=query) |
                                                                 Q(first_name__icontains=query) |
                                                                 Q(last_name__icontains=query))
        # context['articles_list'] = Article.objects.all()[:10]
        return context


# class BookmarkedArticlesView(TemplateView):

articles/templates/articles/articles_by_tags.html
{% extends 'layout/basic.html' %}

{% load humanize %}
{% load static %}

{% block title %}
    #{{ current_tag }}
{% endblock %}

{% block content %}

    <h1 class="mb-4"><i class="bi bi-hash"></i>{{ current_tag }}</h1>

    {% for article in articles_list %}
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <small>
                    {% if user.is_superuser %}
                        <span class="text-secondary me-1"><i class="bi bi-eye-fill me-1"></i>{{ article.views }}</span>
                    {% endif %}
                    {% for tag in article.tags.all %}
                        <a class="text-decoration-none me-1" href="{% url 'articles:articles_by_tags' tag %}">#{{ tag }}</a>
                    {% endfor %}
                </small>
                <h1>
                    <a class="text-decoration-none" href="{% url 'articles:detail_view' article.slug %}">{{ article }}</a>
                </h1>
                <small class="me-1 text-secondary">
                    <b class="me-1">{{ article.post_date|naturalday }}</b>
                    {% if article.author.is_superuser %}
                    <span class="badge bg-dark text-secondary me-1"><em>{{ request.get_host }}</em></span>
                    {% else %}
                    <a style="text-decoration: none;" class="link-secondary me-1" href="{% url 'users:profile_view' article.author.username %}"><em>@{{ article.author.username }}</em></a>
                    {% endif %}
                </small>
                {% if user == article.author %}
                <small>
                    <a href="{% url 'articles:update_view' article.slug %}">Обновить</a>
                    <a href="{% url 'articles:delete_view' article.slug %}">Удалить</a>
                </small>
                {% endif %}
                <p class="mt-4">
                    {{ article.description }}
                </p>
                    {% for security in article.stocks_etfs_or_bonds.all %}
                        <span class="badge border bg-light text-dark">
                            {% if security.icon %}
                                <img src="{{ security.icon.url }}" width="16" alt="{{ security.icon }}" class="align-bottom">
                            {% else %}
                                <img width="16" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                            {% endif %}
                            <a class="text-decoration-none" href="{% url 'securities:security_detail' security.slug %}">
                                {{ security.ticker }}
                            </a>
                        </span>
                    {% endfor %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

articles/templates/articles/bookmarked_articles.html
{% extends 'layout/basic.html' %}

{% load humanize %}
{% load static %}

{% block title %}
    Читать позже
{% endblock %}

{% block content %}

    <h1 class="mb-4"><i class="bi bi-book me-3"></i>Читать позже</h1>

    {% for article in bookemarked_articles %}
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <small>
                    {% for tag in article.tags.all %}
                        <i class="bi bi-hash"></i><a class="text-decoration-none" href="{% url 'articles:articles_by_tags' tag %}">{{ tag }}</a>
                    {% endfor %}
                </small>
                <h1>
                    <a class="text-decoration-none" href="{% url 'articles:detail_view' article.slug %}">{{ article }}</a>
                </h1>
                <small class="me-1">
                    Опубликовано: <a style="text-decoration: none;" class="link-secondary me-1" href="{% url 'users:profile_view' article.author.username %}"><em><b>@{{ article.author.username }}</b></em></a> {{ article.post_date|naturalday }}
                </small>
                {% if user == article.author %}
                <small>
                    <a href="{% url 'articles:update_view' article.slug %}">Обновить</a>
                    <a href="{% url 'articles:delete_view' article.slug %}">Удалить</a>
                </small>
                {% endif %}
                <p class="mt-4">
                    {{ article.description }}
                </p>
                    {% for security in article.stocks_etfs_or_bonds.all %}
                        <span class="badge border bg-light text-dark">
                            {% if security.icon %}
                                <img src="{{ security.icon.url }}" width="16" alt="{{ security.icon }}" class="align-bottom">
                            {% else %}
                                <img width="16" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                            {% endif %}
                            <a class="text-decoration-none" href="{% url 'securities:security_detail' security.slug %}">
                                {{ security.ticker }}
                            </a>
                        </span>
                    {% endfor %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

articles/templates/articles/delete_view.html
{% extends 'layout/basic.html' %}

{% block title %}
    Удалить публикацию?
{% endblock %}

{% block content %}
    <h1 class="mb-4">
        Удалить публикации {{ article_delete }}?
    </h1>

    <br>

    <form method="post">
        {% csrf_token %}
        <p>
            Вы уверены что хотите удалить публикацию <b>{{ article_delete }}</b>?
        </p>
        <input class="btn btn-danger" type="submit" value="Удалить">
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{{ object.get_absolute_url }}">Назад</a>
{% endblock %}

articles/templates/articles/detail_view.html
{% extends 'layout/basic.html' %}

{% load humanize %}
{% load static %}
{% load comments %}
{% load django_bootstrap5 %}

{% block title %}
    {{ object }}
{% endblock %}

{% block content %}
<div class="alert alert-warning d-flex align-items-center" role="alert">
    <i class="bi bi-exclamation-circle me-2" style="font-size: 24px;"></i>
  <div>
    Ни одна публикация, ни любой другой материал, опубликаванные на этом сайте, не являются инвестиционными рекомендациями!
  </div>
</div>
<div class="mb-5">
    <h1>
        <div class="d-flex justify-content-start">
            {{ article.title }}
            <form class="ms-5" action="{% url 'articles:bookmark_article' article.slug %}" method="post">
                {% csrf_token %}
                {% if user.is_authenticated %}
                    {% if bookmarked %}
                        <button class="btn btn-outline-light border" type="submit" name="article_id" value="{{ article.id }}">
                            <i class="bi bi-bookmark-check-fill text-success fs-5"></i>
                        </button>
                    {% else %}
                        <button class="btn btn-outline-light border" type="submit" name="article_id" value="{{ article.id }}">
                            <i class="bi bi-bookmark text-success fs-5"></i>
                        </button>
                    {% endif %}
                {% endif %}
            </form>
        </div>



    </h1>
    <a class="link-secondary" href="
        {% if article.author.is_superuser %}
            {% url 'articles:list_view' %}
        {% else %}
            {% url 'users:profile_view' article.author.username %}
        {% endif %}" style="text-decoration: none;">
        {% if article.author.is_superuser %}

        {% else %}
            {% if article.author.photo %}
                <img width="24" height="24" class="rounded-circle mb-2" src="{{ article.author.photo.url }}" alt="">
            {% else %}
                <i class="bi bi-person-circle text-dark" style="font-size: 24px;"></i>
            {% endif %}
        {% endif %}
        {% if article.author.is_superuser %}
                            <span class="badge bg-dark text-secondary me-1"><em>{{ request.get_host }}</em></span>
                    {% else %}
        <em class="text-secondary">@{{ article.author.username }}</em>
        {% endif %}
    </a>
    <br>
    <small class="me-1">
        Опубликовано: {{ article.post_date|naturalday }}
    </small>
    {% if user == article.author %}
    <small>
        <a href="{% url 'articles:update_view' article.slug %}">Обновить</a>
    </small>
    <small>
        <a href="{% url 'articles:delete_view' article.slug %}">Удалить</a>
    </small>
    {% endif %}
</div>

<div class="mb-5">
    <div>
        {% if article.title_image %}
            <img src="{{ article.title_image.url }}" width="50%" alt="{{ article.title }}" class="border rounded">
        {% endif %}
    </div>

    <p>
        {{ article.body|safe }}
    </p>
</div>

    <p>
        {% for tag in article.tags.all %}
            #<a href="{% url 'articles:articles_by_tags' tag %}">{{ tag }}</a>
        {% endfor %}
    </p>
    <hr>
    <p>
        {% for security in article.stocks_etfs_or_bonds.all %}
            <span class="badge border bg-light text-dark">
                {% if security.icon %}
                    <img src="{{ security.icon.url }}" width="16" alt="{{ security.icon }}" class="align-bottom">
                {% else %}
                    <img width="16" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                {% endif %}
                <a href="{% url 'securities:security_detail' security.slug %}">
                    {{ security.ticker }}
                </a>
            </span>





        {% endfor %}



<div class="mx-md-5">


            <h3 class="my-4">Комментарии {% get_comment_count for article as comment_count %} {% if comment_count %}<span class="badge bg-light text-dark border rounded-pill"> {{ comment_count }}</span>{% endif %}</h3>

        {% if comment_count %}
            {% get_comment_list for article as comment_list %}



            {% for comment in comment_list %}
                <div class="card text-dark bg-light mb-3">
                    <div class="card-body">
                      <small class="card-title mb-3">
                          <a class="" href="{% if comment.user.is_superuser %}
                                        {% url 'articles:list_view' %}
                                    {% else %}
                                        {% url 'users:profile_view' comment.user.username %}
                                    {% endif %}" style="text-decoration: none;">

                          {% if comment.user.photo %}
                              {% if comment.user.is_superuser %}

                            {% else %}
                                <img width="24" height="24" class="rounded-circle me-1" src="{{ comment.user.photo.url }}" alt="">
                            {% endif %}

                          {% else %}
                            <i class="bi bi-person-circle text-dark" style="font-size: 24px;"></i>
                          {% endif %}
                              {% if comment.user.is_superuser %}
                            <span class="badge bg-dark text-secondary me-1"><em>{{ request.get_host }}</em></span>
                    {% else %}
                          <span class="link-secondary">

                              <em>
                                  @{{ comment.user }}
                              </em>
                          </span>
                              {% endif %}
                          </a>
                      </small>
                      <p class="card-text mt-1 mb-1">
                          {{ comment.comment }}
                      </p>
                      <p class="card-text mt-1"><small class="text-muted">{{ comment.submit_date|naturaltime }}</small></p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}

        {% if user.is_authenticated %}
            {% get_comment_form for article as form %}
            <form action="{% comment_form_target %}" method="POST" class="form">
                {% csrf_token %}
                {% bootstrap_field form.comment show_label=False %}
                {% bootstrap_field form.honeypot show_label=False %}
                {% bootstrap_field form.content_type %}
                {% bootstrap_field form.object_pk %}
                {% bootstrap_field form.timestamp %}
                {% bootstrap_field form.security_hash %}
                {% bootstrap_button button_type="submit" content="Отправить" size='sm' button_class='btn btn-primary'  %}
                <input type="hidden" name="next" value="{% url 'articles:detail_view' article.slug %}" />
            </form>
        {% else %}
            <p>Пожалуйста, <a href="{% url 'users:login' %}">войдите</a>, чтобы оставить комментарий.</p>
        {% endif %}

<br>
    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>
</div>
    </div>





{% endblock %}