articles/urls.py
from django.urls import path, re_path

from .views import ArticlesList, ArticleDetail, ArticleCreate, ArticleUpdate, ArticleDelete, ArticlesByTagsList, SearchView
from .views import TagAutocomplete, SecurityAutocomplete, BookmarkArticleView, bookmarked_articles
from stocksetfsbonds.models import StockETFBond

app_name = 'articles'

urlpatterns = [
    path('tag-autocomplete/', TagAutocomplete.as_view(), name='tag-autocomplete'),
    path('security-autocomplete/', SecurityAutocomplete.as_view(), name='security-autocomplete'),
    path('', ArticlesList.as_view(), name='list_view'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('<tag>/', ArticlesByTagsList.as_view(), name='articles_by_tags'),
    path('articles/create/', ArticleCreate.as_view(), name='create_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/$', ArticleDetail.as_view(), name='detail_view'),
    # path('articles/<slug:slug>', ArticleDetail.as_view(), name='detail_view'),

    # path('articles/<slug:slug>/', ArticleUpdate.as_view(), name='update_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/update/$', ArticleUpdate.as_view(), name='update_view'),
    # path('articles/<slug:slug>/delete/', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^articles/(?P<slug>[\w-]+)/delete/$', ArticleDelete.as_view(), name='delete_view'),
    re_path(r'^bookmark/(?P<slug>[\w-]+)/$', BookmarkArticleView, name='bookmark_article'),
    # path('bookmark/<slug:slug>', BookmarkArticleView, name='bookmark_article'),
    path('bookmarked/articles/', bookmarked_articles, name='bookmarked_articles'),
]

stocksetfsbonds/urls.py
from django.urls import path

from .views import SecuritiesList, SecurityDetail, SecurityCreate, Watchlist, WatchlistView, SecurityUpdate

app_name = 'securities'

urlpatterns = [
    path('create/', SecurityCreate.as_view(), name='security_create'),
    path('update/<slug:slug>', SecurityUpdate.as_view(), name='security_update'),
    path('<slug:slug>/', SecuritiesList.as_view(), name='securities_list'),
    path('<slug:slug>', SecurityDetail.as_view(), name='security_detail'),
    path('watchlist/<slug:slug>', Watchlist, name='in_watchlist'),
    path('watchlist/securities/', WatchlistView, name='watchlist'),
]

users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, profile, ChangeUserInfoView, UserPasswordChangeVeiw, RegisterUserView, RegisterDoneView
from .views import DeleteUserView, ProfileView, PrivacyView


app_name = 'users'

urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    # path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    # path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    # path('accounts/profile/<username>/', ProfileView.as_view(), name='profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/<username>/', ProfileView.as_view(), name='profile_view'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', UserPasswordChangeVeiw.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('privacy', PrivacyView.as_view(), name='privacy'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articles.views import TagAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('securities/', include('stocksetfsbonds.urls')),
    path('', include('users.urls')),

    path('comments/', include('django_comments.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

from .utilities import user_photo_directory_path


class AdvUser(AbstractUser):
    photo = models.ImageField(blank=True, verbose_name='Фотография', upload_to=user_photo_directory_path)
    description = models.TextField(blank=True, verbose_name='Обо мне')

users/forms.py
from django.utils.translation import ugettext as _

from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse, reverse_lazy
from django.utils.functional import lazy
from django.utils.safestring import mark_safe

from .models import AdvUser

from captcha.fields import CaptchaField


class ChangedUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('photo', 'username', 'email', 'first_name', 'last_name', 'description')

#
# class RegisterUserForm(forms.ModelForm):
#     email = forms.EmailField(required=True, label='Адрес электронной почты')
#     password1 = forms.CharField(label='Пароль',
#                                 widget=forms.PasswordInput,
#                                 help_text=password_validation.password_validators_help_text_html())
#     password2 = forms.CharField(label='Пароль повторно',
#                                 widget=forms.PasswordInput,
#                                 help_text='Введите тот же самый пароль ещё раз для проверки')
#     captcha = CaptchaField(label='Введите текст с картинки ', error_messages={'invalid': 'Неправильный текст'}, generator='captcha.helpers.math_challenge')
#
#     def clean_password1(self):
#         password1 = self.cleaned_data['password1']
#         if password1:
#             password_validation.validate_password(password1)
#         return password1
#
#     def clean(self):
#         super(RegisterUserForm, self).clean()
#         password1 = self.cleaned_data['password1']
#         password2 = self.cleaned_data['password2']
#         if password1 and password2 and password1 != password2:
#             errors = {'password2': ValidationError(
#                 'Введённые пароли не совпадают', code='password_mismatch')}
#             raise ValidationError(errors)
#
#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.set_password(self.cleaned_data['password1'])
#         if commit:
#             user.save()
#         return user
#
#     class Meta:
#         model = AdvUser
#         fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'photo', 'description', 'captcha')
#


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    # check = forms.BooleanField(label=lazy(lambda: _("Privacy <a href='%s' a>policy</a>" % reverse('users:privacy'))))
    # check = forms.BooleanField(required=True, label=mark_safe("I accept the terms and <a href='{%s}'>conditions.</a>" % reverse_lazy('users:privacy')))
    check = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['check'].label = mark_safe('Принимаю <a target="_blank" href=%s> политику конфиденциальности</a>' % reverse_lazy('users:privacy'))

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'check')

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages

from taggit.models import Tag

from articles.models import Article
from stocksetfsbonds.models import StocksETFsBonds
from .models import AdvUser
from .forms import ChangedUserInfoForm, RegisterUserForm


class UserLoginView(LoginView):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


@login_required
def profile(request):
    user_articles = Article.objects.filter(author=request.user.pk)
    bookemarked_articles = Article.objects.filter(bookmark=request.user.pk)
    tags_list = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
    securities_types_list = StocksETFsBonds.objects.all()
    context = {'user_articles': user_articles, 'tags_list': tags_list, 'securities_types_list': securities_types_list, 'bookemarked_articles': bookemarked_articles}
    return render(request, 'users/profile.html', context)

#
# class ProfileView(LoginRequiredMixin, DetailView):
#     model = AdvUser
#     template_name = 'users/profile.html'
#     # необходимо для указания адреса в шаблоне
#     slug_field = 'username'
#     # необходимо чтобы заработал маршрут в urls.py
#     slug_url_kwarg = 'username'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#
#         # 5 тегов с наиболшим количством публикаций
#         context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
#             '-articles_quantiy')[:10]
#         context['securities_types_list'] = StocksETFsBonds.objects.all()
#         # context['articles_list'] = Article.objects.all()[:10]
#         return context


class UserLogoutView(SuccessMessageMixin, LoginRequiredMixin, LogoutView):
    template_name = 'users/logout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'users/change_user_info.html'
    form_class = ChangedUserInfoForm
    success_url = reverse_lazy('users:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


class UserPasswordChangeVeiw(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:profile')
    success_message = 'Пароль пользователя изменён'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


class RegisterUserView(SuccessMessageMixin, CreateView):
    model = AdvUser
    template_name = 'users/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('articles:list_view')
    success_message = 'Вы успешно зарегистрировались!'

    def form_valid(self, form):
        valid = super(RegisterUserView, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user)
        return valid

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


class RegisterDoneView(TemplateView):
    template_name = 'users/register_done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'users/delete_user.html'
    success_url = reverse_lazy('articles:list_view')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удалён')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context


class ProfileView(DetailView):
    model = AdvUser
    template_name = 'users/profile_view.html'
    # необходимо для указания адреса в шаблоне
    slug_field = 'username'
    # необходимо чтобы заработал маршрут в urls.py
    slug_url_kwarg = 'username'
    context_object_name = 'user_profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        context['user_profile_articles'] = Article.objects.filter(author=self.object.pk, published=True)
        return context


class PrivacyView(TemplateView):
    template_name = 'users/privacy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 5 тегов с наиболшим количством публикаций
        context['tags_list'] = Tag.objects.annotate(articles_quantiy=Count('taggit_taggeditem_items')).order_by(
            '-articles_quantiy')[:10]
        context['securities_types_list'] = StocksETFsBonds.objects.all()
        # context['articles_list'] = Article.objects.all()[:10]
        return context

users/templates/users/change_user_info.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    {{ user.username }}
{% endblock %}

{% block content %}

    <h1 class="mb-4">Правка личных данных пользователя {{ user.username }}</h1>



    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
    <a class="btn btn-outline-primary my-4" href="{% url 'users:password_change' %}" role="button">Изменить пароль</a>
    <a class="btn btn-danger my-4" href="{% url 'users:profile_delete' %}" role="button">Удалить аккаунт</a><br>
        {% bootstrap_button button_type="submit" content="Сохранить" %}
    </form>



    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

users/templates/users/delete_user.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    {{ user.username }}
{% endblock %}

{% block content %}

    <h1 class="mb-4">{{ user.username }}, вы уверены, что хотите удалить свою учётную запись?</h1>

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" button_class="btn-danger" content="Удалить" %}
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

users/templates/users/login.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    Авторизация
{% endblock %}

{% block content %}

    <h1 class="mb-4">Авторизация</h1>

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <p class="mb-4">Или <a href="{% url 'users:register' %}">зарегистрируйтесь</a></p>
        {% bootstrap_button button_type="submit" content="Войти" %}
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

users/templates/users/logout.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    Выход
{% endblock %}

{% block content %}

    <h1 class="mb-4">Выход</h1>

    <p>
        Вы успешно вышли из сайта.
    </p>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

users/templates/users/password_change.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    Смена пароля
{% endblock %}

{% block content %}

    <h1 class="mb-4">Смена пароля пользователя {{ user.username }}</h1>

    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% bootstrap_button button_type="submit" content="Обновить пароль" %}
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

users/templates/users/profile.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}
{% load humanize %}
{% load static %}

{% block title %}
    {{ user.username }}
{% endblock %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="row align-items-center border rounded mb-5">
        <div class="col-2">
            {% if user.photo %}
                <img class="rounded-circle my-3 mx-2" src="{{ user.photo.url }}" width="64" height="64" alt="{{ user.username }}">
            {% else %}
                <i class="bi bi-person-circle m-2" style="font-size: 64px;"></i>
            {% endif %}
        </div>
        <div class="col-10 p-3">
                        <h1 class="mb-0">
                {% if user.first_name %}
                    {{ user.first_name }} {{ user.last_name }}
                {% endif %}
            </h1>
            <span class="text-secondary"><em>@{{ user.username }}</em></span>
        </div>
    </div>
        </div>
        <div class="col-md">
            <br>
            <a class="btn btn-warning ms-4" href="{% url 'articles:create_view' %}" role="button"><i class="bi bi-pencil-square me-2"></i>Новая публикация</a>
            <a id="btn" class="btn p-0 ms-4" href="{% url 'articles:bookmarked_articles' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Список для чтения"><i class="bi bi-book fs-3 text-dark"></i></a>
        </div>
    </div>

</div>

    <h1 class="mb-4">Мои публикации</h1>
    {% for article in user_articles %}
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <small>
                    <span class="text-secondary me-1"><i class="bi bi-eye-fill me-1"></i>{{ article.views }}</span>
                    {% for tag in article.tags.all %}
                        <a class="text-decoration-none me-1" href="{% url 'articles:articles_by_tags' tag %}">#{{ tag }}</a>
                    {% endfor %}
                </small>
                <h1>
                    <a class="text-decoration-none" href="{% url 'articles:detail_view' article.slug %}">{{ article }}</a>
                </h1>
                <small class="me-1">
                    <b class="">{{ article.post_date|naturalday }}</b>
                                        {% if not article.published %}
                        <span class="badge bg-primary text-white"><em>Черновой</em></span>

                    {% endif %}
                </small>
                {% if user == article.author %}
                <small>
                    <a href="{% url 'articles:update_view' article.slug %}">Обновить</a>
                    <a href="{% url 'articles:delete_view' article.slug %}">Удалить</a>
                </small>
                {% endif %}
                <p class="mt-4">
                    {{ article.description }}
                </p>
                {% for security in article.stocks_etfs_or_bonds.all %}
                    <span class="badge border bg-light text-dark">
                        {% if security.icon %}
                            <img src="{{ security.icon.url }}" width="16" alt="{{ security.icon }}" class="align-bottom">
                        {% else %}
                            <img width="16" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                        {% endif %}
                        <a class="text-decoration-none" href="{% url 'securities:security_detail' security.slug %}">
                            {{ security.ticker }}
                        </a>
                    </span>
                {% endfor %}
            </div>
        </div>
    {% empty %}
        <p class="mb-3">У вас нет публикаций. <a class="link-warning" href="{% url 'articles:create_view' %}" role="button">Станьте автором</a></p>
    {% endfor %}




    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>


{% endblock %}

users/templates/users/profile_view.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}
{% load humanize %}
{% load static %}

{% block title %}
    @{{ user_profile.username }}
{% endblock %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="row align-items-center border rounded mb-5">
        <div class="col-2">
            {% if user_profile.photo %}
                <img class="rounded-circle my-3 mx-2" src="{{ user_profile.photo.url }}" width="64" height="64" alt="{{ user_profile.username }}">
            {% else %}
                <i class="bi bi-person-circle m-2" style="font-size: 64px;"></i>
            {% endif %}
        </div>
        <div class="col-10 p-3">
            <h1 class="mb-0">
                {% if user_profile.first_name %}
                    {{ user_profile.first_name }} {{ user_profile.last_name }}
                {% endif %}
            </h1>
            <span class="text-secondary"><em>@{{ user_profile.username }}</em></span>
        </div>
    </div>
        </div>
        <div class="col">

        </div>
    </div>

</div>

    <h1 class="mb-4">Публикации пользователя <span class="text-secondary"><em>@{{ user_profile.username }}</em></span></h1>

    {% for article in user_profile_articles %}
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <small>
                    {% if user.is_superuser %}
                        <span class="text-secondary me-1"><i class="bi bi-eye-fill me-1"></i>{{ article.views }}</span>
                    {% endif %}
                    {% for tag in article.tags.all %}
                        <a class="text-decoration-none me-1" href="{% url 'articles:articles_by_tags' tag %}">#{{ tag }}</a>
                    {% endfor %}
                </small>
                <h1>
                    <a class="text-decoration-none" href="{% url 'articles:detail_view' article.slug %}">{{ article }}</a>
                </h1>
                <small class="me-1">
                    <b class="me-1">{{ article.post_date|naturalday }}</b>
                </small>
                {% if user == article.author %}
                <small>
                    <a href="{% url 'articles:update_view' article.slug %}">Обновить</a>
                    <a href="{% url 'articles:delete_view' article.slug %}">Удалить</a>
                </small>
                {% endif %}
                <p class="mt-4">
                    {{ article.description }}
                </p>
                {% for security in article.stocks_etfs_or_bonds.all %}
                    <span class="badge border bg-light text-dark">
                        {% if security.icon %}
                            <img src="{{ security.icon.url }}" width="16" alt="{{ security.icon }}" class="align-bottom">
                        {% else %}
                            <img width="16" src="{% static 'stocksetfsbonds/img/museum.png' %}" alt="{{ security.name }}" class="align-bottom">
                        {% endif %}
                        <a class="text-decoration-none" href="{% url 'securities:security_detail' security.slug %}">
                            {{ security.ticker }}
                        </a>
                    </span>
                {% endfor %}
            </div>
        </div>
    {% empty %}
        У пользователя ещё нет публикаций.
    {% endfor %}

{% endblock %}

users/templates/users/register_done.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    Регистрация завершена
{% endblock %}

{% block content %}

    <h1 class="mb-4">Регистрация завершена</h1>
    <p>
        Регистрация пользователя завершена.
    </p>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'articles:list_view' %}">Назад</a>

{% endblock %}

users/templates/users/register_user.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}

    <h1 class="mb-4">Регистрация нового пользователя</h1>

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Зарегистрироваться" %}
    </form>


{% endblock %}